version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mqttconf/config/:/mosquitto/config/:ro
      - ./mqttconf/log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  web:
    image: iotapp:1.0
    build: .
    command: >
      sh -c "python3 manage.py makemigrations && \
             python3 manage.py migrate && \
             python manage.py collectstatic --noinput && \
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRETKEY=&w!-%qsbcb_7kdo^)roirk)evgkhu1vn(e8tztam-*+n1b#)=2
      - ALLOWEDHOST=*
      - DB_NAME=iotappdb
      - DB_USER=iotappdbuser
      - DB_PASSWORD=swe599.
      - DB_HOST=localhost
      - DB_PORT=3306
      - EMAIL_HOST_USER=fatihcirak@gmail.com
      - EMAIL_HOST_PASSWORD=IHJvrNcO6jYPZqGn
      - MQTT_SERVER=192.168.56.102
      - MQTT_PORT=1883
      - MQTT_KEEPALIVE=60
    ports:
      - "80:8000"
    volumes:
      - ./src:/app
      - /var/run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock

volumes:
  data: ~